spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/g_38_jp_shop
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: qwerty007
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
key:
  access: W0s9WxTNJzUzDGzG0iVvYs2n711wA1B4pE4xHY4pbI0=
  refresh: 2AU7vBC7gJVlh/72A5BpWq6qTquDCv77K4rs87O0PQ0=